
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipLabel = new javax.swing.JLabel();
        connectButton = new javax.swing.JButton();
        ipAddressTextField = new javax.swing.JTextField();
        mainLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 300));
        getContentPane().setLayout(null);

        ipLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IP Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei", 1, 10), new java.awt.Color(255, 0, 51))); // NOI18N
        getContentPane().add(ipLabel);
        ipLabel.setBounds(190, 140, 140, 58);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(connectButton);
        connectButton.setBounds(200, 210, 130, 23);
        getContentPane().add(ipAddressTextField);
        ipAddressTextField.setBounds(200, 160, 120, 20);

        mainLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(0, 204, 204));
        mainLabel.setText("R E M O T E   S E A R C H   E N G I N E");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(30, 10, 290, 20);

        imageLabel.setIcon(new javax.swing.ImageIcon("E:\\JAY KUMAR\\Java Programms\\PROGRMS\\NetWorking\\Remote Search Engine\\login.png")); // NOI18N
        getContentPane().add(imageLabel);
        imageLabel.setBounds(10, 50, 180, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed

        dispose();
    }//GEN-LAST:event_connectButtonActionPerformed

public String getIpAddress(){
    return (ipAddressTextField.getText());
}   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField ipAddressTextField;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
