/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import bean.Cheque;
import database.DatabaseManager;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.DateFormatter;
import utility.TypeEncoder;

/**
 *
 * @author Jay Kumar
 */
public class ChequeFrame extends javax.swing.JFrame {

    /**
     * Creates new form Cheque
     */
    DefaultTableModel tableModel;
    
    static int ACCOUNT_COLUMN =0;
    static int GIVEN_DATE_COLUMN =1;
    static int CHEQUE_NO_COLUMN =2;
    static int CHEQUE_DATE_COLUMN =3;
    
    public ChequeFrame() {
        initComponents();
        tableModel = (DefaultTableModel)chequeTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        accountTypeComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        chequeTable = new javax.swing.JTable();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        toDateChooser = new com.toedter.calendar.JDateChooser();
        showButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 382));
        getContentPane().setLayout(null);

        mainLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(102, 0, 0));
        mainLabel.setText("CHEQUE BOOK");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(170, 0, 160, 50);

        accountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Purchase", "Sale", "Cash", "Credit" }));
        accountTypeComboBox.setMinimumSize(new java.awt.Dimension(500, 380));
        accountTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                accountTypeComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(accountTypeComboBox);
        accountTypeComboBox.setBounds(350, 10, 110, 30);

        chequeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account", "Given Date", "Cheque Number", "Cheque Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(chequeTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 95, 450, 238);
        getContentPane().add(fromDateChooser);
        fromDateChooser.setBounds(10, 64, 145, 20);

        jLabel1.setText("TO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(165, 64, 20, 20);
        getContentPane().add(toDateChooser);
        toDateChooser.setBounds(189, 64, 181, 20);

        showButton.setText("SHOW");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showButton);
        showButton.setBounds(376, 61, 80, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_accountTypeComboBoxItemStateChanged
        System.out.println(evt.getItem());
        
    }//GEN-LAST:event_accountTypeComboBoxItemStateChanged

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        Date from = fromDateChooser.getDate();
        Date to = toDateChooser.getDate();
        if(from == null || to == null){
            JOptionPane.showMessageDialog(this, "Please Add Both Date.. ");
            return;
        }
        String fromDate = DateFormatter.dateToStringYMD(from);
        String toDate = DateFormatter.dateToStringYMD(to);
        List list = DatabaseManager.getData("SELECT ch FROM "+Cheque.class.getName()+" as ch JOIN ch.account ac WHERE ac.accountType="+ TypeEncoder.encode((String)accountTypeComboBox.getSelectedItem())+" AND ch.givenDate>='"+fromDate+"' AND ch.givenDate<='"+toDate+"' ","CHEQUE_ID ASC");
        clearTable();
        for(int i=0;i<list.size();i++){
            
            Cheque ch = (Cheque)list.get(i);
            int row = tableModel.getRowCount();
            tableModel.insertRow(row, new Object[]{});
            tableModel.setValueAt(ch.getAccount().getAccountName(), row, ACCOUNT_COLUMN);
            tableModel.setValueAt(ch.getGivenDate(), row, GIVEN_DATE_COLUMN);
            tableModel.setValueAt(ch.getChequeNumber(), row, CHEQUE_NO_COLUMN);
            tableModel.setValueAt(ch.getChequeDate(), row, CHEQUE_DATE_COLUMN);
        }
        
    }//GEN-LAST:event_showButtonActionPerformed

    private void clearTable(){
        int rows = tableModel.getRowCount();
        for(int i=0;i<rows;i++){
            tableModel.removeRow(0);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountTypeComboBox;
    private javax.swing.JTable chequeTable;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton showButton;
    private com.toedter.calendar.JDateChooser toDateChooser;
    // End of variables declaration//GEN-END:variables
}
