
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BooksCategoryFrame.java
 *
 * Created on Dec 2, 2012, 11:29:20 AM
 */
/**
 *
 * @author DELL
 */
public class BooksCategoryFrame extends javax.swing.JFrame {

    /** Creates new form BooksCategoryFrame */
    public BooksCategoryFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booksListScrollPane = new javax.swing.JScrollPane();
        booksList = new javax.swing.JList();
        mainLabel = new javax.swing.JLabel();
        booksListLabel = new javax.swing.JLabel();
        categoryIdLabel = new javax.swing.JLabel();
        accessNoTextField = new javax.swing.JTextField();
        remarksLabel = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        editionLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        yearOfPublishingLabel = new javax.swing.JLabel();
        accessNoLabel = new javax.swing.JLabel();
        drasNoLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        purchaseFormLabel = new javax.swing.JLabel();
        dateOfPurchaseLabel = new javax.swing.JLabel();
        publishingYearChooser = new com.toedter.calendar.JYearChooser();
        purchaseFromTextField = new javax.swing.JTextField();
        drasNoTextField = new javax.swing.JTextField();
        isbnTextField = new javax.swing.JTextField();
        purchaseDateChooser = new com.toedter.calendar.JDateChooser();
        categoryIdTextField = new javax.swing.JTextField();
        bookNameTextField = new javax.swing.JTextField();
        publisherTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        editionTextField = new javax.swing.JTextField();
        volumeTextField = new javax.swing.JTextField();
        remarksScrollPane = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        priceFormattedTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        booksList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                booksListValueChanged(evt);
            }
        });
        booksListScrollPane.setViewportView(booksList);

        getContentPane().add(booksListScrollPane);
        booksListScrollPane.setBounds(407, 78, 210, 420);

        mainLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        mainLabel.setText("B O O K S   D E T A I L S");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(210, 10, 210, 30);

        booksListLabel.setText("Books");
        getContentPane().add(booksListLabel);
        booksListLabel.setBounds(490, 50, 40, 14);

        categoryIdLabel.setText("Category Id");
        getContentPane().add(categoryIdLabel);
        categoryIdLabel.setBounds(30, 80, 70, 20);
        getContentPane().add(accessNoTextField);
        accessNoTextField.setBounds(90, 360, 100, 20);

        remarksLabel.setText("Remarks");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(30, 470, 70, 14);

        bookNameLabel.setText("Book Name");
        getContentPane().add(bookNameLabel);
        bookNameLabel.setBounds(30, 130, 70, 20);

        publisherLabel.setText("Publisher");
        getContentPane().add(publisherLabel);
        publisherLabel.setBounds(30, 170, 70, 14);

        authorLabel.setText("Author");
        getContentPane().add(authorLabel);
        authorLabel.setBounds(30, 210, 70, 14);

        editionLabel.setText("Edition");
        getContentPane().add(editionLabel);
        editionLabel.setBounds(30, 250, 70, 14);

        volumeLabel.setText("Volume");
        getContentPane().add(volumeLabel);
        volumeLabel.setBounds(30, 290, 70, 14);

        isbnLabel.setText("ISBN");
        getContentPane().add(isbnLabel);
        isbnLabel.setBounds(200, 320, 40, 20);

        yearOfPublishingLabel.setText("Year Of Publishing");
        getContentPane().add(yearOfPublishingLabel);
        yearOfPublishingLabel.setBounds(30, 320, 100, 14);

        accessNoLabel.setText("Access No.");
        getContentPane().add(accessNoLabel);
        accessNoLabel.setBounds(30, 360, 60, 20);

        drasNoLabel.setText("Dras. No");
        getContentPane().add(drasNoLabel);
        drasNoLabel.setBounds(200, 360, 50, 20);

        priceLabel.setText("Price");
        getContentPane().add(priceLabel);
        priceLabel.setBounds(30, 400, 60, 20);

        purchaseFormLabel.setText("Purchase From");
        getContentPane().add(purchaseFormLabel);
        purchaseFormLabel.setBounds(30, 440, 100, 20);

        dateOfPurchaseLabel.setText("Date Of Purchase");
        getContentPane().add(dateOfPurchaseLabel);
        dateOfPurchaseLabel.setBounds(180, 400, 90, 20);
        getContentPane().add(publishingYearChooser);
        publishingYearChooser.setBounds(127, 320, 60, 20);
        getContentPane().add(purchaseFromTextField);
        purchaseFromTextField.setBounds(110, 440, 280, 20);
        getContentPane().add(drasNoTextField);
        drasNoTextField.setBounds(250, 360, 130, 20);
        getContentPane().add(isbnTextField);
        isbnTextField.setBounds(240, 320, 140, 20);
        getContentPane().add(purchaseDateChooser);
        purchaseDateChooser.setBounds(270, 400, 130, 20);

        categoryIdTextField.setEditable(false);
        getContentPane().add(categoryIdTextField);
        categoryIdTextField.setBounds(110, 80, 90, 20);
        getContentPane().add(bookNameTextField);
        bookNameTextField.setBounds(110, 130, 280, 20);
        getContentPane().add(publisherTextField);
        publisherTextField.setBounds(110, 170, 280, 20);
        getContentPane().add(authorTextField);
        authorTextField.setBounds(110, 210, 280, 20);
        getContentPane().add(editionTextField);
        editionTextField.setBounds(110, 250, 280, 20);
        getContentPane().add(volumeTextField);
        volumeTextField.setBounds(110, 290, 280, 20);

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        remarksScrollPane.setViewportView(remarksTextArea);

        getContentPane().add(remarksScrollPane);
        remarksScrollPane.setBounds(110, 470, 280, 40);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(40, 520, 120, 23);

        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeButton);
        removeButton.setBounds(170, 520, 120, 23);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(300, 520, 120, 23);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(430, 520, 120, 23);
        getContentPane().add(priceFormattedTextField);
        priceFormattedTextField.setBounds(70, 400, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booksListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_booksListValueChanged
        
        CategoryDetialBean bean = (CategoryDetialBean) booksList.getSelectedValue();
        this.accessNoTextField.setText(bean.getAccessNo());
        this.authorTextField.setText(bean.getAuthor());
        this.categoryIdTextField.setText(""+bean.getCatDetailId());
        this.purchaseDateChooser.setDate(bean.getDateOfPurchase());
        this.drasNoTextField.setText(bean.getDrasNo());
        this.editionTextField.setText(bean.getEdition());
        this.isbnTextField.setText(bean.getIsbn());
        this.bookNameTextField.setText(bean.getName());
        this.priceFormattedTextField.setText(""+bean.getPrise());
        this.publisherTextField.setText(bean.getPublisher());
        this.purchaseFromTextField.setText(bean.getPurchaseFrom());
        this.remarksTextArea.setText(bean.getRemarks());
        this.volumeTextField.setText(bean.getVolume());
        this.publishingYearChooser.setValue(bean.getYearOfPublishing());
    }//GEN-LAST:event_booksListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String name = bookNameTextField.getText();
        String publish = publisherTextField.getText();
        String author = authorTextField.getText();
        String edi = editionTextField.getText();
        String vol = volumeTextField.getText();
        int publishYear = this.publishingYearChooser.getYear();
        String isbn = isbnTextField.getText();
        String access = accessNoTextField.getText();
        String drasNo = drasNoTextField.getText();
        int price = Integer.parseInt(priceFormattedTextField.getText());
        String purch = purchaseFromTextField.getText();
        java.util.Date date= this.purchaseDateChooser.getDate();
        try{
            DatabaseManager.addcategory_detial(name, publish
                , author, edi, vol, publishYear, isbn, access, drasNo, price, purch, date, remarksTextArea.getText());
            JOptionPane.showMessageDialog(null,"Record has been added Successfuly...");
            updateList();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        CategoryDetialBean bean = (CategoryDetialBean)this.booksList.getSelectedValue();
        if(bean==null){
            JOptionPane.showMessageDialog(null, "No any selected value...");
            return;
        }
        try{
            DatabaseManager.deletecategory_detial(bean.getCatDetailId());
            JOptionPane.showMessageDialog(null,"record has successfully deleted..");
            updateList();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_removeButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        CategoryDetialBean bean = (CategoryDetialBean)this.booksList.getSelectedValue();
        if(bean==null){
            JOptionPane.showMessageDialog(null, "No any selected value...");
            return;
        }
        int id = bean.getCatDetailId();
        String name = bookNameTextField.getText();
        String publish = publisherTextField.getText();
        String author = authorTextField.getText();
        String edi = editionTextField.getText();
        String vol = volumeTextField.getText();
        int publishYear = this.publishingYearChooser.getYear();
        String isbn = isbnTextField.getText();
        String access = accessNoTextField.getText();
        String drasNo = drasNoTextField.getText();
        int price = Integer.parseInt((String)priceFormattedTextField.getText().trim());
        String purch = purchaseFromTextField.getText();
        java.util.Date date= this.purchaseDateChooser.getDate();
        try{
            DatabaseManager.updatecategory_detial(id ,name, publish
                , author, edi, vol, publishYear, isbn, access, drasNo, price, purch, date, remarksTextArea.getText());
            JOptionPane.showMessageDialog(null,"Record has been updated Successfuly...");
            updateList();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,date.getMonth());

    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        categoryIdTextField.setText("");
        bookNameTextField.setText("");
        publisherTextField.setText("");
        authorTextField.setText("");
        editionTextField.setText("");
        volumeTextField.setText("");
        isbnTextField.setText("");
        drasNoTextField.setText("");
        accessNoTextField.setText("");
        priceFormattedTextField.setText("");
        purchaseFromTextField.setText("");
        remarksTextArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed
  
    public void setVisible(){
        try{
            updateList();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
            ex.printStackTrace();
        }
        setVisible(true);
        
    }
    public void updateList()throws Exception{
        Vector v = DatabaseManager.getAllcategory_detial();
        booksList.setListData(v);
        System.out.println("size:"+v.size());
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accessNoLabel;
    private javax.swing.JTextField accessNoTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JList booksList;
    private javax.swing.JLabel booksListLabel;
    private javax.swing.JScrollPane booksListScrollPane;
    private javax.swing.JLabel categoryIdLabel;
    private javax.swing.JTextField categoryIdTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dateOfPurchaseLabel;
    private javax.swing.JLabel drasNoLabel;
    private javax.swing.JTextField drasNoTextField;
    private javax.swing.JLabel editionLabel;
    private javax.swing.JTextField editionTextField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField priceFormattedTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField publisherTextField;
    private com.toedter.calendar.JYearChooser publishingYearChooser;
    private com.toedter.calendar.JDateChooser purchaseDateChooser;
    private javax.swing.JLabel purchaseFormLabel;
    private javax.swing.JTextField purchaseFromTextField;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JScrollPane remarksScrollPane;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JTextField volumeTextField;
    private javax.swing.JLabel yearOfPublishingLabel;
    // End of variables declaration//GEN-END:variables
}
