/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on Nov 6, 2012, 7:29:55 PM
 */
/**
 *
 * @author Jay Kumar
 */
public class Frame extends javax.swing.JFrame {

    /** Creates new form Frame */
    public Frame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        driveLabel = new javax.swing.JLabel();
        driveComboBox = new javax.swing.JComboBox();
        searchNameLabel = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        filesScrollPane = new javax.swing.JScrollPane();
        filesList = new javax.swing.JList();
        onlineUserScrollPane = new javax.swing.JScrollPane();
        onlineUserList = new javax.swing.JList();
        fileNameLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        fileSizeLabel = new javax.swing.JLabel();
        packetSizeLabel = new javax.swing.JLabel();
        totalPacketLabel = new javax.swing.JLabel();
        lastPacketLabel = new javax.swing.JLabel();
        packetNoLabel = new javax.swing.JLabel();
        permissionButton = new javax.swing.JButton();
        restrictionButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        userListLabel = new javax.swing.JLabel();
        fileListLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(255, 102, 102));
        mainLabel.setText("Remote Search Engine");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(170, 10, 150, 15);

        driveLabel.setText("Drives");
        getContentPane().add(driveLabel);
        driveLabel.setBounds(10, 30, 50, 14);

        getContentPane().add(driveComboBox);
        driveComboBox.setBounds(10, 50, 100, 20);

        searchNameLabel.setText("Search File Name:");
        getContentPane().add(searchNameLabel);
        searchNameLabel.setBounds(10, 80, 100, 14);
        getContentPane().add(fileNameTextField);
        fileNameTextField.setBounds(10, 100, 100, 20);

        filesScrollPane.setViewportView(filesList);

        getContentPane().add(filesScrollPane);
        filesScrollPane.setBounds(190, 50, 140, 250);

        onlineUserScrollPane.setViewportView(onlineUserList);

        getContentPane().add(onlineUserScrollPane);
        onlineUserScrollPane.setBounds(340, 50, 120, 220);

        fileNameLabel.setText("File Name:");
        getContentPane().add(fileNameLabel);
        fileNameLabel.setBounds(10, 130, 170, 14);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshButton);
        refreshButton.setBounds(110, 50, 80, 20);

        fileSizeLabel.setText("File Size:");
        getContentPane().add(fileSizeLabel);
        fileSizeLabel.setBounds(10, 160, 170, 14);

        packetSizeLabel.setText("Packet size:");
        getContentPane().add(packetSizeLabel);
        packetSizeLabel.setBounds(10, 190, 170, 14);

        totalPacketLabel.setText("Total Packet:");
        getContentPane().add(totalPacketLabel);
        totalPacketLabel.setBounds(10, 220, 170, 14);

        lastPacketLabel.setText("Last Packet:");
        getContentPane().add(lastPacketLabel);
        lastPacketLabel.setBounds(10, 250, 170, 14);

        packetNoLabel.setText("Packet #");
        getContentPane().add(packetNoLabel);
        packetNoLabel.setBounds(10, 280, 170, 14);

        permissionButton.setText("Permission");
        permissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(permissionButton);
        permissionButton.setBounds(340, 280, 120, 23);

        restrictionButton.setText("Restriction");
        restrictionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restrictionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(restrictionButton);
        restrictionButton.setBounds(340, 310, 120, 23);

        downloadButton.setText("Download");
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(downloadButton);
        downloadButton.setBounds(190, 310, 140, 23);

        progressBar.setStringPainted(true);
        getContentPane().add(progressBar);
        progressBar.setBounds(10, 310, 170, 20);

        userListLabel.setText("Online User ");
        getContentPane().add(userListLabel);
        userListLabel.setBounds(360, 30, 70, 14);

        fileListLabel.setText("Searched Files");
        getContentPane().add(fileListLabel);
        fileListLabel.setBounds(210, 30, 80, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void permissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permissionButtonActionPerformed

    private void restrictionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restrictionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restrictionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadButton;
    private javax.swing.JComboBox driveComboBox;
    private javax.swing.JLabel driveLabel;
    private javax.swing.JLabel fileListLabel;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JLabel fileSizeLabel;
    private javax.swing.JList filesList;
    private javax.swing.JScrollPane filesScrollPane;
    private javax.swing.JLabel lastPacketLabel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JList onlineUserList;
    private javax.swing.JScrollPane onlineUserScrollPane;
    private javax.swing.JLabel packetNoLabel;
    private javax.swing.JLabel packetSizeLabel;
    private javax.swing.JButton permissionButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton restrictionButton;
    private javax.swing.JLabel searchNameLabel;
    private javax.swing.JLabel totalPacketLabel;
    private javax.swing.JLabel userListLabel;
    // End of variables declaration//GEN-END:variables
}
