package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private String accountName;
     private String address;
     private int accountType;
     private String mobileNo;
     private String remarks;
     private boolean isDeleted;
     private Set cheques = new HashSet(0);
     private Set transactions = new HashSet(0);
     private Set salePurchases = new HashSet(0);

    public Account() {
    }

	
    public Account(String accountName, String address, int accountType, String mobileNo, String remarks, boolean isDeleted) {
        this.accountName = accountName;
        this.address = address;
        this.accountType = accountType;
        this.mobileNo = mobileNo;
        this.remarks = remarks;
        this.isDeleted = isDeleted;
    }
    public Account(String accountName, String address, int accountType, String mobileNo, String remarks, boolean isDeleted, Set cheques, Set transactions, Set salePurchases) {
       this.accountName = accountName;
       this.address = address;
       this.accountType = accountType;
       this.mobileNo = mobileNo;
       this.remarks = remarks;
       this.isDeleted = isDeleted;
       this.cheques = cheques;
       this.transactions = transactions;
       this.salePurchases = salePurchases;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(int accountType) {
        this.accountType = accountType;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }
    public Set getSalePurchases() {
        return this.salePurchases;
    }
    
    public void setSalePurchases(Set salePurchases) {
        this.salePurchases = salePurchases;
    }


    @Override
    public String toString() {
        return accountName; //To change body of generated methods, choose Tools | Templates.
    }


}


