package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import utility.DateFormatter;

/**
 * Day generated by hbm2java
 */
public class Day  implements java.io.Serializable {


     private Integer dayId;
     private Year year;
     private Date day;
     private String remarks;
     private double cash;
     private Set transactions = new HashSet(0);
     private Set salePurchases = new HashSet(0);

    public Day() {
    }

	
    public Day(Year year, Date day, String remarks, double cash) {
        this.year = year;
        this.day = day;
        this.remarks = remarks;
        this.cash = cash;
    }
    public Day(Year year, Date day, String remarks, double cash, Set transactions, Set salePurchases) {
       this.year = year;
       this.day = day;
       this.remarks = remarks;
       this.cash = cash;
       this.transactions = transactions;
       this.salePurchases = salePurchases;
    }
   
    public Integer getDayId() {
        return this.dayId;
    }
    
    public void setDayId(Integer dayId) {
        this.dayId = dayId;
    }
    public Year getYear() {
        return this.year;
    }
    
    public void setYear(Year year) {
        this.year = year;
    }
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public double getCash() {
        return this.cash;
    }
    
    public void setCash(double cash) {
        this.cash = cash;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }
    public Set getSalePurchases() {
        return this.salePurchases;
    }
    
    public void setSalePurchases(Set salePurchases) {
        this.salePurchases = salePurchases;
    }

    @Override
    public String toString() {
        return DateFormatter.dateToStringDMY(day); //To change body of generated methods, choose Tools | Templates.
    }


}


