package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MeasurementUnit generated by hbm2java
 */
public class MeasurementUnit  implements java.io.Serializable {


     private Integer unitId;
     private String unitName;
     private String remarks;
     private Set products = new HashSet(0);

    public MeasurementUnit() {
    }

	
    public MeasurementUnit(String unitName, String remarks) {
        this.unitName = unitName;
        this.remarks = remarks;
    }
    public MeasurementUnit(String unitName, String remarks, Set products) {
       this.unitName = unitName;
       this.remarks = remarks;
       this.products = products;
    }
   
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }

    @Override
    public String toString() {
        return unitName; //To change body of generated methods, choose Tools | Templates.
    }


}


