package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private MeasurementUnit measurementUnit;
     private Categeory categeory;
     private String productName;
     private double rate;
     private double currentRate;
     private double originalRate;
     private double quantity;
     private String remarks;
     private Set transactions = new HashSet(0);

    public Product() {
    }

	
    public Product(MeasurementUnit measurementUnit, Categeory categeory, String productName, double rate, double currentRate, double originalRate, double quantity, String remarks) {
        this.measurementUnit = measurementUnit;
        this.categeory = categeory;
        this.productName = productName;
        this.rate = rate;
        this.currentRate = currentRate;
        this.originalRate = originalRate;
        this.quantity = quantity;
        this.remarks = remarks;
    }
    public Product(MeasurementUnit measurementUnit, Categeory categeory, String productName, double rate, double currentRate, double originalRate, double quantity, String remarks, Set transactions) {
       this.measurementUnit = measurementUnit;
       this.categeory = categeory;
       this.productName = productName;
       this.rate = rate;
       this.currentRate = currentRate;
       this.originalRate = originalRate;
       this.quantity = quantity;
       this.remarks = remarks;
       this.transactions = transactions;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public MeasurementUnit getMeasurementUnit() {
        return this.measurementUnit;
    }
    
    public void setMeasurementUnit(MeasurementUnit measurementUnit) {
        this.measurementUnit = measurementUnit;
    }
    public Categeory getCategeory() {
        return this.categeory;
    }
    
    public void setCategeory(Categeory categeory) {
        this.categeory = categeory;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }
    public double getCurrentRate() {
        return this.currentRate;
    }
    
    public void setCurrentRate(double currentRate) {
        this.currentRate = currentRate;
    }
    public double getOriginalRate() {
        return this.originalRate;
    }
    
    public void setOriginalRate(double originalRate) {
        this.originalRate = originalRate;
    }
    public double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }


    @Override
    public String toString() {
        return productName; //To change body of generated methods, choose Tools | Templates.
    }

}


