package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SalePurchase generated by hbm2java
 */
public class SalePurchase  implements java.io.Serializable {


     private Integer salePurchaseId;
     private Day day;
     private Account account;
     private double totalAmount;
     private int type;
     private String remarks;
     private double paidAmount;
     private Set cheques = new HashSet(0);
     private Set transactions = new HashSet(0);

    public SalePurchase() {
    }

	
    public SalePurchase(Day day, Account account, double totalAmount, int type, String remarks, double paidAmount) {
        this.day = day;
        this.account = account;
        this.totalAmount = totalAmount;
        this.type = type;
        this.remarks = remarks;
        this.paidAmount = paidAmount;
    }
    public SalePurchase(Day day, Account account, double totalAmount, int type, String remarks, double paidAmount, Set cheques, Set transactions) {
       this.day = day;
       this.account = account;
       this.totalAmount = totalAmount;
       this.type = type;
       this.remarks = remarks;
       this.paidAmount = paidAmount;
       this.cheques = cheques;
       this.transactions = transactions;
    }
   
    public Integer getSalePurchaseId() {
        return this.salePurchaseId;
    }
    
    public void setSalePurchaseId(Integer salePurchaseId) {
        this.salePurchaseId = salePurchaseId;
    }
    public Day getDay() {
        return this.day;
    }
    
    public void setDay(Day day) {
        this.day = day;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public double getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(double paidAmount) {
        this.paidAmount = paidAmount;
    }
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }

    @Override
    public String toString() {
        String s = utility.TypeDecoder.decode(type)+"-";
        if(account!=null)s+=account.getAccountName()+"-";
        if(paidAmount!=0)s+=""+paidAmount;
        if(totalAmount!=0)s+=""+totalAmount;
        return s; //To change body of generated methods, choose Tools | Templates.
    }


}


