package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA



/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer transactionId;
     private Day day;
     private Account account;
     private Product product;
     private SalePurchase salePurchase;
     private double quantity;
     private double amount;
     private int type;
     private Double productOriginalRate;

    public Transaction() {
    }

	
    public Transaction(Day day, Account account, Product product, SalePurchase salePurchase, double quantity, double amount, int type) {
        this.day = day;
        this.account = account;
        this.product = product;
        this.salePurchase = salePurchase;
        this.quantity = quantity;
        this.amount = amount;
        this.type = type;
    }
    public Transaction(Day day, Account account, Product product, SalePurchase salePurchase, double quantity, double amount, int type, Double productOriginalRate) {
       this.day = day;
       this.account = account;
       this.product = product;
       this.salePurchase = salePurchase;
       this.quantity = quantity;
       this.amount = amount;
       this.type = type;
       this.productOriginalRate = productOriginalRate;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public Day getDay() {
        return this.day;
    }
    
    public void setDay(Day day) {
        this.day = day;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public SalePurchase getSalePurchase() {
        return this.salePurchase;
    }
    
    public void setSalePurchase(SalePurchase salePurchase) {
        this.salePurchase = salePurchase;
    }
    public double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(double quantity) {
        this.quantity = quantity;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Double getProductOriginalRate() {
        return this.productOriginalRate;
    }
    
    public void setProductOriginalRate(Double productOriginalRate) {
        this.productOriginalRate = productOriginalRate;
    }




}


