package bean;
// Generated Oct 30, 2013 2:08:02 AM by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String password;

    public User() {
    }

    public User(String userName, String password) {
       this.userName = userName;
       this.password = password;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Override
    public String toString() {
        return userName;
    }

    

}


