package bean;
// Generated Oct 29, 2013 9:01:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Year generated by hbm2java
 */
public class Year  implements java.io.Serializable {


     private Integer yearId;
     private int year;
     private String remarks;
     private Set daies = new HashSet(0);

    public Year() {
    }

	
    public Year(int year, String remarks) {
        this.year = year;
        this.remarks = remarks;
    }
    public Year(int year, String remarks, Set daies) {
       this.year = year;
       this.remarks = remarks;
       this.daies = daies;
    }
   
    public Integer getYearId() {
        return this.yearId;
    }
    
    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getDaies() {
        return this.daies;
    }
    
    public void setDaies(Set daies) {
        this.daies = daies;
    }

    @Override
    public String toString() {
        return ""+year; //To change body of generated methods, choose Tools | Templates.
    }


}


