import java.awt.FileDialog;
import java.sql.SQLException;

import javax.swing.event.ListSelectionEvent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GramForm.java
 *
 * Created on Sep 22, 2012, 11:27:25 PM
 */
/**
 *
 * @author Jay Kumar
 */
public class GramForm extends javax.swing.JFrame {

    /** Creates new form GramForm */
    public GramForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceLbl = new javax.swing.JLabel();
        SourceTxt = new javax.swing.JTextField();
        BrowseBtn = new javax.swing.JButton();
        GenerateBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gramList = new javax.swing.JList();
        AddBtn = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        catLbl = new javax.swing.JLabel("Categories");
      
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gram Form");

        sourceLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sourceLbl.setText("Source");

        BrowseBtn.setText("Browse");
        BrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseBtnActionPerformed(evt);
            }
        });
        
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionperformed();
            }
        });

        
        GenerateBtn.setText("Generate");
        GenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        gramList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        gramList.setVisibleRowCount(7);
        jScrollPane1.setViewportView(gramList);

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sourceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(BrowseBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                .addComponent(GenerateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(catLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(169, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseBtn)
                    .addComponent(SourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catLbl)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(GenerateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn)
                    .addComponent(AddBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void GenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBtnActionPerformed
        // TODO add your handling code here:
    	try{
    		gramList.removeAll();
    		java.io.File f = new java.io.File(SourceTxt.getText());
    		java.io.DataInputStream in = new java.io.DataInputStream(new java.io.FileInputStream(f));
    		String fileTxt="";
    		String s="";
    		while((s=in.readLine())!=null){
    			fileTxt+=s;
    		}
    		this.grams=N_Gram.nGram(fileTxt, 3);
    		gramList.setListData(grams);
    	}
    	catch(Exception e){
    		javax.swing.JOptionPane.showMessageDialog(this, "file not exist...!");
    	}
    }//GEN-LAST:event_GenerateBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
    	gramList.setListData(new java.util.Vector());
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    	CategoryBean bean = (CategoryBean)combo.getSelectedItem();
    	
    	if(bean == null || grams==null){ javax.swing.JOptionPane.showMessageDialog(this, " Not Selected any Category or no any gram.."); return; }
    	int i=0;
    	try{
    	for(int k=0;k<grams.length;k++ )
    		i = DataBaseManager.addGrams(bean.getCatID(), grams[k]);
    	}catch(SQLException e){ e.printStackTrace();}
    	if(i>0)javax.swing.JOptionPane.showMessageDialog(this,"grams successfully inserted...");
    	gramList.setListData(new java.util.Vector());
    	grams=null;
    }//GEN-LAST:event_AddBtnActionPerformed

    private void BrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseBtnActionPerformed
        // TODO add your handling code here:
    	java.awt.FileDialog dialog = new FileDialog(this,"Open",FileDialog.LOAD);
        dialog.setVisible(true);
        String source = dialog.getDirectory()+ dialog.getFile();
        this.SourceTxt.setText(source);
    }//GEN-LAST:event_BrowseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void setVisible(boolean b){
    	getCategories();
    	super.setVisible(b);
    }
    
    public void getCategories(){
    	try{
    		combo.removeAllItems();
    		java.util.Vector v = DataBaseManager.getCategories();
    		Object[] obj = v.toArray();
    		 for(int i=0; i<obj.length; i++){
    			 combo.addItem((CategoryBean)obj[i]);
    		 }
    	}
    	catch(Exception e){ e.printStackTrace();}
    }
    
    private void comboActionperformed(){
    	CategoryBean cBean = (CategoryBean)combo.getSelectedItem();
    	  try {
			java.util.Vector v =DataBaseManager.getGramFromCategory(cBean.CatID);
			gramList.setListData(v);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BrowseBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JTextField SourceTxt;
    private javax.swing.JList gramList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sourceLbl;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel catLbl;
    private static String grams[]= null;
    // End of variables declaration//GEN-END:variables
}
