/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jay
 */
public class Main extends javax.swing.JFrame {

    double a1, a2, a3;
    double b1, b2, b3;
    double c1, c2, c3;
    double d1, d2, d3;
    double x=0, y=0, z=0;
    int counter = 1;
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b1TextField = new javax.swing.JTextField();
        c1TextField = new javax.swing.JTextField();
        d1TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        a2TextField = new javax.swing.JTextField();
        b2TextField = new javax.swing.JTextField();
        c2TextField = new javax.swing.JTextField();
        d2TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        a3TextField = new javax.swing.JTextField();
        b3TextField = new javax.swing.JTextField();
        c3TextField = new javax.swing.JTextField();
        d3TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        solveButton = new javax.swing.JButton();
        approximationTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 400));
        getContentPane().setLayout(null);
        getContentPane().add(a1TextField);
        a1TextField.setBounds(50, 70, 40, 30);

        jLabel1.setText("Jaccobi Solution");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 150, 20);
        getContentPane().add(b1TextField);
        b1TextField.setBounds(100, 70, 30, 30);
        getContentPane().add(c1TextField);
        c1TextField.setBounds(140, 70, 30, 30);
        getContentPane().add(d1TextField);
        d1TextField.setBounds(200, 70, 60, 30);

        jLabel2.setText("=");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 70, 20, 30);
        getContentPane().add(a2TextField);
        a2TextField.setBounds(60, 130, 30, 30);
        getContentPane().add(b2TextField);
        b2TextField.setBounds(100, 130, 30, 30);
        getContentPane().add(c2TextField);
        c2TextField.setBounds(140, 130, 30, 30);
        getContentPane().add(d2TextField);
        d2TextField.setBounds(200, 130, 60, 30);

        jLabel3.setText("=");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 130, 20, 40);
        getContentPane().add(a3TextField);
        a3TextField.setBounds(60, 180, 30, 30);
        getContentPane().add(b3TextField);
        b3TextField.setBounds(100, 180, 30, 30);
        getContentPane().add(c3TextField);
        c3TextField.setBounds(140, 180, 30, 30);
        getContentPane().add(d3TextField);
        d3TextField.setBounds(200, 180, 59, 30);

        jLabel4.setText("=");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 170, 20, 40);

        jLabel5.setText("Third Equation");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 80, 14);

        jLabel6.setText("First Equation");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 40, 90, 14);

        jLabel7.setText("Second Equation");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 100, 80, 14);

        solveButton.setText("Solve");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(solveButton);
        solveButton.setBounds(160, 220, 90, 30);

        approximationTextField.setText("1");
        approximationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approximationTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(approximationTextField);
        approximationTextField.setBounds(90, 220, 60, 30);

        jLabel8.setText("Approximation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 224, 80, 20);

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(286, 30, 420, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        this.resultTextArea.setText("");
        a1 = Integer.parseInt(a1TextField.getText());
        b1 = Integer.parseInt(b1TextField.getText());
        c1 = Integer.parseInt(c1TextField.getText());
        d1 = Integer.parseInt(d1TextField.getText());
        a2 = Integer.parseInt(a2TextField.getText());
        b2 = Integer.parseInt(b2TextField.getText());
        c2 = Integer.parseInt(c2TextField.getText());
        d2 = Integer.parseInt(d2TextField.getText());
        a3 = Integer.parseInt(a3TextField.getText());
        b3 = Integer.parseInt(b3TextField.getText());
        c3 = Integer.parseInt(c3TextField.getText());
        d3 = Integer.parseInt(d3TextField.getText());
        counter = Integer.parseInt(this.approximationTextField.getText());
        for(int i=1;i<=counter;i++){
            
//            System.out.println("----------------------");
//            System.out.print("x"+i+" =1/"+a1+" ("+d1+"-"+b1+"("+y+" ) - "+c1+"("+z+"))  =: ");
            resultTextArea.setText(resultTextArea.getText()+"----------------------\n");
            resultTextArea.setText(resultTextArea.getText()+"x"+i+" =1/"+a1+" ("+d1+"-"+b1+"("+y+" ) - "+c1+"("+z+"))  =: ");
            x = (1/a1)*(d1-(b1*y)-(c1*z));
            resultTextArea.setText(resultTextArea.getText()+x+"\n");    
//            System.out.println(x);
            
//            System.out.print("y"+i+" =1/"+b2+" ("+d2+"-"+a2+"("+x+" ) - "+c2+"("+z+" ))  =: ");
            resultTextArea.setText(resultTextArea.getText()+"y"+i+" =1/"+b2+" ("+d2+"-"+a2+"("+x+" ) - "+c2+"("+z+" ))  =: ");
            y = (1/b2)*(d2-(a2*x)-(c2*z));
            resultTextArea.setText(resultTextArea.getText()+y+"\n");
//            System.out.println(y);
            
//            System.out.print("z"+i+" =1/"+c3+" ("+d3+"-"+a3+"("+x+") - "+b3+"("+y+"))  =: ");
            resultTextArea.setText(resultTextArea.getText()+"z"+i+" =1/"+c3+" ("+d3+"-"+a3+"("+x+") - "+b3+"("+y+"))  =: ");
            z = (1/c3)*(d3-(a3*x)-(b3*y));
            resultTextArea.setText(resultTextArea.getText()+z+"\n");
            resultTextArea.setText(resultTextArea.getText()+"----------------------\n");
//            System.out.println(z);
//            System.out.println("----------------------");
            
    }//GEN-LAST:event_solveButtonActionPerformed
    x = 0;
    y = 0;
    z = 0;
    }
    
    private void approximationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approximationTextFieldActionPerformed
        solveButtonActionPerformed(evt);
    }//GEN-LAST:event_approximationTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1TextField;
    private javax.swing.JTextField a2TextField;
    private javax.swing.JTextField a3TextField;
    private javax.swing.JTextField approximationTextField;
    private javax.swing.JTextField b1TextField;
    private javax.swing.JTextField b2TextField;
    private javax.swing.JTextField b3TextField;
    private javax.swing.JTextField c1TextField;
    private javax.swing.JTextField c2TextField;
    private javax.swing.JTextField c3TextField;
    private javax.swing.JTextField d1TextField;
    private javax.swing.JTextField d2TextField;
    private javax.swing.JTextField d3TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton solveButton;
    // End of variables declaration//GEN-END:variables
}
