/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgramFrame.java
 *
 * Created on Oct 12, 2012, 11:37:46 AM
 */
/**
 *
 * @author Jay Kumar
 */
public class ProgramFrame extends javax.swing.JFrame {

    /** Creates new form ProgramFrame */
    public ProgramFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        listScroll = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        depIdLbl = new javax.swing.JLabel();
        progNameTxt = new javax.swing.JTextField();
        depIDTxt = new javax.swing.JTextField();
        progIdLbl = new javax.swing.JLabel();
        remarkLbl = new javax.swing.JLabel();
        remarkScroll = new javax.swing.JScrollPane();
        remarkTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        listLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        facLbl = new javax.swing.JLabel();
        facComboBox = new javax.swing.JComboBox();
        depComboBox = new javax.swing.JComboBox();
        progLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        durationText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 420));
        getContentPane().setLayout(null);

        mainLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(153, 0, 204));
        mainLabel.setText("P r o g r a m   I n f o r m a t i o n");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(110, 10, 260, 30);

        listScroll.setViewportView(list);

        getContentPane().add(listScroll);
        listScroll.setBounds(270, 80, 160, 250);

        depIdLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        depIdLbl.setText("Department ID:");
        getContentPane().add(depIdLbl);
        depIdLbl.setBounds(30, 120, 110, 30);
        getContentPane().add(progNameTxt);
        progNameTxt.setBounds(30, 180, 230, 20);
        getContentPane().add(depIDTxt);
        depIDTxt.setBounds(120, 60, 120, 20);

        progIdLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        progIdLbl.setText("Program ID :");
        getContentPane().add(progIdLbl);
        progIdLbl.setBounds(30, 50, 110, 30);

        remarkLbl.setText("Remarks");
        getContentPane().add(remarkLbl);
        remarkLbl.setBounds(30, 240, 50, 20);

        remarkScroll.setViewportView(remarkTxt);

        getContentPane().add(remarkScroll);
        remarkScroll.setBounds(30, 260, 230, 70);

        addBtn.setText("ADD");
        getContentPane().add(addBtn);
        addBtn.setBounds(20, 340, 70, 30);

        DelBtn.setText("DEL");
        getContentPane().add(DelBtn);
        DelBtn.setBounds(100, 340, 70, 30);

        updateBtn.setText("Update");
        getContentPane().add(updateBtn);
        updateBtn.setBounds(180, 340, 73, 30);

        clearBtn.setText("Clear");
        getContentPane().add(clearBtn);
        clearBtn.setBounds(260, 340, 70, 30);

        listLbl.setText("Program List");
        getContentPane().add(listLbl);
        listLbl.setBounds(310, 50, 80, 30);

        backBtn.setText("Back");
        getContentPane().add(backBtn);
        backBtn.setBounds(340, 340, 70, 30);

        facLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        facLbl.setText("Faculty ID");
        getContentPane().add(facLbl);
        facLbl.setBounds(30, 80, 70, 30);

        getContentPane().add(facComboBox);
        facComboBox.setBounds(100, 90, 150, 20);

        getContentPane().add(depComboBox);
        depComboBox.setBounds(140, 130, 110, 20);

        progLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        progLabel.setText("Program Name");
        getContentPane().add(progLabel);
        progLabel.setBounds(30, 160, 100, 20);

        durationLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        durationLabel.setText("Duration");
        getContentPane().add(durationLabel);
        durationLabel.setBounds(30, 210, 60, 16);
        getContentPane().add(durationText);
        durationText.setBounds(90, 210, 170, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProgramFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox depComboBox;
    private javax.swing.JTextField depIDTxt;
    private javax.swing.JLabel depIdLbl;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField durationText;
    private javax.swing.JComboBox facComboBox;
    private javax.swing.JLabel facLbl;
    private javax.swing.JList list;
    private javax.swing.JLabel listLbl;
    private javax.swing.JScrollPane listScroll;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel progIdLbl;
    private javax.swing.JLabel progLabel;
    private javax.swing.JTextField progNameTxt;
    private javax.swing.JLabel remarkLbl;
    private javax.swing.JScrollPane remarkScroll;
    private javax.swing.JTextField remarkTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
