/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentFrame.java
 *
 * Created on Oct 12, 2012, 12:22:17 PM
 */
/**
 *
 * @author Jay Kumar
 */
public class StudentFrame extends javax.swing.JFrame {

    /** Creates new form StudentFrame */
    public StudentFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        facLbl = new javax.swing.JLabel();
        facComboBox = new javax.swing.JComboBox();
        depIdLbl = new javax.swing.JLabel();
        depComboBox = new javax.swing.JComboBox();
        progLbl = new javax.swing.JLabel();
        batchComboBox = new javax.swing.JComboBox();
        batchLabel = new javax.swing.JLabel();
        progComboBox1 = new javax.swing.JComboBox();
        listScroll = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        listLbl = new javax.swing.JLabel();
        stdIdTxt = new javax.swing.JTextField();
        stdIdLabel = new javax.swing.JLabel();
        shiftTxt = new javax.swing.JTextField();
        shiftLabel = new javax.swing.JLabel();
        groupTxt = new javax.swing.JTextField();
        groupLabel = new javax.swing.JLabel();
        stdNameTxt = new javax.swing.JTextField();
        stdNameLabel = new javax.swing.JLabel();
        fNameTxt = new javax.swing.JTextField();
        fNameLabel = new javax.swing.JLabel();
        surnameTxt = new javax.swing.JTextField();
        surnameLabel = new javax.swing.JLabel();
        rollNoTxt = new javax.swing.JTextField();
        RollLabel = new javax.swing.JLabel();
        remarkLbl = new javax.swing.JLabel();
        remarkScroll = new javax.swing.JScrollPane();
        remarkTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 560));
        getContentPane().setLayout(null);

        mainLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(153, 0, 204));
        mainLabel.setText("S t u d e n t   I n f o r m a t i o n");
        getContentPane().add(mainLabel);
        mainLabel.setBounds(110, 10, 230, 30);

        facLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        facLbl.setText("Faculty");
        getContentPane().add(facLbl);
        facLbl.setBounds(20, 40, 70, 30);

        getContentPane().add(facComboBox);
        facComboBox.setBounds(100, 50, 210, 20);

        depIdLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        depIdLbl.setText("Department");
        getContentPane().add(depIdLbl);
        depIdLbl.setBounds(20, 70, 110, 30);

        getContentPane().add(depComboBox);
        depComboBox.setBounds(100, 80, 210, 22);

        progLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        progLbl.setText("Program");
        getContentPane().add(progLbl);
        progLbl.setBounds(20, 110, 60, 30);

        getContentPane().add(batchComboBox);
        batchComboBox.setBounds(100, 150, 210, 22);

        batchLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        batchLabel.setText("Batch");
        getContentPane().add(batchLabel);
        batchLabel.setBounds(20, 150, 60, 20);

        getContentPane().add(progComboBox1);
        progComboBox1.setBounds(100, 120, 210, 22);

        listScroll.setViewportView(list);

        getContentPane().add(listScroll);
        listScroll.setBounds(320, 70, 150, 340);

        listLbl.setText("Student List");
        getContentPane().add(listLbl);
        listLbl.setBounds(350, 40, 80, 30);
        getContentPane().add(stdIdTxt);
        stdIdTxt.setBounds(100, 180, 100, 20);

        stdIdLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        stdIdLabel.setText("Student ID");
        getContentPane().add(stdIdLabel);
        stdIdLabel.setBounds(20, 180, 70, 20);
        getContentPane().add(shiftTxt);
        shiftTxt.setBounds(100, 210, 100, 20);

        shiftLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftLabel.setText("Shift");
        getContentPane().add(shiftLabel);
        shiftLabel.setBounds(20, 210, 70, 20);
        getContentPane().add(groupTxt);
        groupTxt.setBounds(100, 240, 100, 20);

        groupLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        groupLabel.setText("Group");
        getContentPane().add(groupLabel);
        groupLabel.setBounds(20, 240, 70, 20);
        getContentPane().add(stdNameTxt);
        stdNameTxt.setBounds(110, 270, 200, 20);

        stdNameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        stdNameLabel.setText("Student Name");
        getContentPane().add(stdNameLabel);
        stdNameLabel.setBounds(20, 270, 100, 20);
        getContentPane().add(fNameTxt);
        fNameTxt.setBounds(110, 300, 200, 20);

        fNameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fNameLabel.setText("Father Name");
        getContentPane().add(fNameLabel);
        fNameLabel.setBounds(20, 300, 90, 20);
        getContentPane().add(surnameTxt);
        surnameTxt.setBounds(110, 330, 200, 20);

        surnameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        surnameLabel.setText("Surname");
        getContentPane().add(surnameLabel);
        surnameLabel.setBounds(20, 330, 90, 20);
        getContentPane().add(rollNoTxt);
        rollNoTxt.setBounds(110, 360, 200, 20);

        RollLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RollLabel.setText("Roll No");
        getContentPane().add(RollLabel);
        RollLabel.setBounds(20, 360, 90, 20);

        remarkLbl.setText("Remarks");
        getContentPane().add(remarkLbl);
        remarkLbl.setBounds(20, 380, 50, 20);

        remarkScroll.setViewportView(remarkTxt);

        getContentPane().add(remarkScroll);
        remarkScroll.setBounds(30, 400, 280, 70);

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(10, 480, 90, 30);

        DelBtn.setText("DEL");
        getContentPane().add(DelBtn);
        DelBtn.setBounds(110, 480, 90, 30);

        updateBtn.setText("Update");
        getContentPane().add(updateBtn);
        updateBtn.setBounds(210, 480, 90, 30);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn);
        clearBtn.setBounds(310, 480, 90, 30);

        backBtn.setText("Back");
        getContentPane().add(backBtn);
        backBtn.setBounds(410, 480, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_addBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelBtn;
    private javax.swing.JLabel RollLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox batchComboBox;
    private javax.swing.JLabel batchLabel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox depComboBox;
    private javax.swing.JLabel depIdLbl;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JComboBox facComboBox;
    private javax.swing.JLabel facLbl;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JTextField groupTxt;
    private javax.swing.JList list;
    private javax.swing.JLabel listLbl;
    private javax.swing.JScrollPane listScroll;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JComboBox progComboBox1;
    private javax.swing.JLabel progLbl;
    private javax.swing.JLabel remarkLbl;
    private javax.swing.JScrollPane remarkScroll;
    private javax.swing.JTextField remarkTxt;
    private javax.swing.JTextField rollNoTxt;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JTextField shiftTxt;
    private javax.swing.JLabel stdIdLabel;
    private javax.swing.JTextField stdIdTxt;
    private javax.swing.JLabel stdNameLabel;
    private javax.swing.JTextField stdNameTxt;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
