/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Employee_info.java
 *
 * Created on Nov 9, 2012, 2:37:30 PM
 */
/**
 *
 * @author Jay Kumar
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTable.PrintMode;
import net.proteanit.sql.DbUtils;
public class Employee_info extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet result = null;
    PreparedStatement pst= null;
    /** Creates new form Employee_info */
    public Employee_info() {
        initComponents();
        conn= JavaConnect.connectDB();
        update_table();
        fillCombo();
        currentDate();
    }
private void update_table(){
    try{
        String sql = "Select * from Employeeinfo";
        pst = conn.prepareStatement(sql);
        result = pst.executeQuery();
        Table_Employee.setModel(DbUtils.resultSetToTableModel(result));
    }catch(Exception ex){JOptionPane.showInternalMessageDialog(null, ex);
            }
    finally{
        try{
            result.close();
            pst.close();
        }catch(Exception ex){}
    }
}
 private void fillCombo(){
    try{
        String sql = "Select * from Employeeinfo";
        pst = conn.prepareStatement(sql);
        result = pst.executeQuery();
        
        while(result.next()){
            String name = result.getString("name");
            ComboBox_name.addItem(name);
        }
    }catch(Exception ex){JOptionPane.showInternalMessageDialog(null, ex);}
    finally{
        try{
            result.close();
            pst.close();
        }catch(Exception ex){}
    }
}
 
 public void comboSelect(){
     int d = this.ComboBox_name.getSelectedIndex();
     if(d==1){
         Userinfo_frame uf = new Userinfo_frame();
         uf.setVisible(true);
     }
     if(d==2){
         Login_jframe lf = new Login_jframe();
         lf.setVisible(true);
     }
 
 }
    /** This method is called from within the constructor to
     * nitialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Employee = new javax.swing.JTable();
        ComboBox_name = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        closeToolButton = new javax.swing.JButton();
        helpToolButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        employeeInfoPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        date = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        Table_Employee.setForeground(new java.awt.Color(51, 0, 204));
        Table_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Employee.setToolTipText("Employee info table");
        Table_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EmployeeMouseClicked(evt);
            }
        });
        Table_Employee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_EmployeeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Employee);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(285, 40, 370, 275);

        ComboBox_name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBox_namePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(ComboBox_name);
        ComboBox_name.setBounds(20, 80, 140, 22);

        jToolBar1.setRollover(true);

        closeToolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Button-Close-icon.png"))); // NOI18N
        closeToolButton.setToolTipText("close");
        closeToolButton.setFocusable(false);
        closeToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        closeToolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeToolButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(closeToolButton);

        helpToolButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Help-icon.png"))); // NOI18N
        helpToolButton.setToolTipText("help");
        helpToolButton.setFocusable(false);
        helpToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        helpToolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpToolButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(helpToolButton);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 670, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(50, 290, 110, 22);

        employeeInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 0, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        employeeInfoPanel.setLayout(null);

        idLabel.setText("Emploeeid");
        employeeInfoPanel.add(idLabel);
        idLabel.setBounds(10, 30, 60, 20);

        nameLabel.setText("Name");
        employeeInfoPanel.add(nameLabel);
        nameLabel.setBounds(10, 60, 50, 20);

        ageLabel.setText("Age");
        employeeInfoPanel.add(ageLabel);
        ageLabel.setBounds(10, 120, 40, 16);

        surnameLabel.setText("Surname");
        employeeInfoPanel.add(surnameLabel);
        surnameLabel.setBounds(10, 90, 60, 20);
        employeeInfoPanel.add(ageTextField);
        ageTextField.setBounds(70, 120, 70, 22);
        employeeInfoPanel.add(idTextField);
        idTextField.setBounds(70, 30, 70, 22);

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(255, 0, 0));
        employeeInfoPanel.add(nameTextField);
        nameTextField.setBounds(70, 60, 70, 20);
        employeeInfoPanel.add(surnameTextField);
        surnameTextField.setBounds(70, 90, 70, 22);

        getContentPane().add(employeeInfoPanel);
        employeeInfoPanel.setBounds(10, 120, 150, 170);

        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 0, 255)));
        buttonPanel.setLayout(null);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Save-icon.png"))); // NOI18N
        saveButton.setText("save");
        saveButton.setToolTipText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);
        saveButton.setBounds(10, 15, 100, 20);

        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton2);
        jButton2.setBounds(10, 40, 100, 25);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Remove-Male-User-icon.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setToolTipText("Delete the selected row");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(deleteButton);
        deleteButton.setBounds(10, 70, 100, 25);

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Apps-system-software-update-icon.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.setToolTipText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(updateButton);
        updateButton.setBounds(10, 100, 100, 25);

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Actions-edit-clear-icon.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.setToolTipText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(clearButton);
        clearButton.setBounds(10, 133, 100, 20);

        getContentPane().add(buttonPanel);
        buttonPanel.setBounds(160, 120, 120, 160);

        searchTextField.setToolTipText("Search (Employeeid , name , surname)");
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchTextField);
        searchTextField.setBounds(30, 50, 150, 22);

        searchLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        getContentPane().add(searchLabel);
        searchLabel.setBounds(20, 30, 170, 50);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printButton);
        printButton.setBounds(190, 40, 80, 25);

        jMenu1.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New ");
        jMenu1.add(newMenuItem);
        jMenu1.add(jSeparator1);

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        closeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Button-Close-icon.png"))); // NOI18N
        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenuItem);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        date.setText("jMenu3");
        jMenuBar1.add(date);

        helpMenu.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Help file");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem1);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EmployeeMouseClicked

            int row = Table_Employee.getSelectedRow();
            idTextField.setText(Table_Employee.getModel().getValueAt(row, 0).toString());
            nameTextField.setText(Table_Employee.getModel().getValueAt(row, 1).toString());
            surnameTextField.setText(Table_Employee.getModel().getValueAt(row, 2).toString());
            String age = Table_Employee.getModel().getValueAt(row, 3).toString();
            ageTextField.setText(age);
            
            if((Integer.parseInt(age))>=25){
                ageTextField.setBackground(Color.GREEN);
                ageTextField.setForeground(Color.black);
            }
            else{
                ageTextField.setBackground(Color.red);
                ageTextField.setForeground(Color.yellow);
            }
    }//GEN-LAST:event_Table_EmployeeMouseClicked

    private void ComboBox_namePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBox_namePopupMenuWillBecomeInvisible
        comboSelect();
        try{
            String name =(String) ComboBox_name.getSelectedItem();
            String sql = "Select * from Employeeinfo where name =? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, name);
            result = pst.executeQuery();
            if(result.next()){
                idTextField.setText(result.getString("employeeid"));
                nameTextField.setText(result.getString("name"));
                surnameTextField.setText(result.getString("surname"));
                ageTextField.setText(result.getString("age"));
                
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ComboBox_namePopupMenuWillBecomeInvisible

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        close();
    }//GEN-LAST:event_closeMenuItemActionPerformed

    private void closeToolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeToolButtonActionPerformed
        close();
    }//GEN-LAST:event_closeToolButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try{
            String sql = "Insert into Employeeinfo (employeeid , name , surname , age) values (? , ? , ? , ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, idTextField.getText());
            pst.setString(2 , nameTextField.getText());
            pst.setString(3 , surnameTextField.getText());
            pst.setString(4, ageTextField.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Saved");
            update_table();
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new Userinfo_frame().setVisible(true);
//        close();
//        Userinfo_frame s = new Userinfo_frame();
//        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
            int i = JOptionPane.showConfirmDialog(null, "Do you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
            if(i==0){
                try{
                    String sql = "Delete from Employeeinfo where employeeid = ?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, idTextField.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Deleted");
                    update_table();
                }   catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex);
                }
            }  
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       try{
           String value1 = idTextField.getText();
           String value2 = nameTextField.getText();
           String value3 = surnameTextField.getText();
           String value4 = ageTextField.getText();
           String sql = "Update Employeeinfo set employeeid = '"+value1+"' , name = '"+value2+"' , surname = '"+value3+"' , age = '"+value4+"' where employeeid = "+value1;
           pst = conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null, "updated");
           update_table();
        }
        catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        idTextField.setText("");
        nameTextField.setText("");
        surnameTextField.setText("");
        ageTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
        try{
            String sql = "Select * from Employeeinfo where name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, searchTextField.getText());
            result = pst.executeQuery();
            if(result.next()){
                String add1 = result.getString("employeeid");
                idTextField.setText(add1);
                String add2 = result.getString("name");
                nameTextField.setText(add2);
                String add3 = result.getString("surname");
                surnameTextField.setText(add3);
                String add4 = result.getString("age");
                ageTextField.setText(add4);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        try{
            String sql = "Select * from Employeeinfo where employeeid = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, searchTextField.getText());
            result = pst.executeQuery();
            if(result.next()){
                String add1 = result.getString("employeeid");
                idTextField.setText(add1);
                String add2 = result.getString("name");
                nameTextField.setText(add2);
                String add3 = result.getString("surname");
                surnameTextField.setText(add3);
                String add4 = result.getString("age");
                ageTextField.setText(add4);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        try{
            String sql = "Select * from Employeeinfo where surname = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, searchTextField.getText());
            result = pst.executeQuery();
            if(result.next()){
                String add1 = result.getString("employeeid");
                idTextField.setText(add1);
                String add2 = result.getString("name");
                nameTextField.setText(add2);
                String add3 = result.getString("surname");
                surnameTextField.setText(add3);
                String add4 = result.getString("age");
                ageTextField.setText(add4);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_searchTextFieldKeyReleased

    private void Table_EmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_EmployeeKeyPressed
        int row=1;
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            row = Table_Employee.getSelectedRow()+1;            
        }
        else if(evt.getKeyCode()==KeyEvent.VK_UP){
            row = Table_Employee.getSelectedRow()-1;
        }
        idTextField.setText(Table_Employee.getModel().getValueAt(row, 0).toString());
        nameTextField.setText(Table_Employee.getModel().getValueAt(row, 1).toString());
        surnameTextField.setText(Table_Employee.getModel().getValueAt(row, 2).toString());
        ageTextField.setText(Table_Employee.getModel().getValueAt(row, 3).toString());
    }//GEN-LAST:event_Table_EmployeeKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"Help.txt");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void helpToolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpToolButtonActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"Help.txt");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_helpToolButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int e =JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if(e==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        MessageFormat header = new MessageFormat("Report print");
        MessageFormat footer = new MessageFormat("Page{0,Number,integer}");
        try{
            this.Table_Employee.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch(Exception e){
            System.err.format("Cannot Print %s%n", e);
        }
    }//GEN-LAST:event_printButtonActionPerformed
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    public void currentDate(){
        Calendar calen = new GregorianCalendar();
        int month = calen.get(Calendar.MONTH);
        int year = calen.get(Calendar.YEAR);
        int day = calen.get(Calendar.DAY_OF_MONTH);
        int second = calen.get(Calendar.SECOND);
        int min = calen.get(Calendar.MINUTE);
        int hour = calen.get(Calendar.HOUR);
        date.setText(day+"/"+month+"/"+year+"  "+hour+":"+min+":"+second);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Employee_info().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_name;
    private javax.swing.JTable Table_Employee;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JButton closeToolButton;
    private javax.swing.JMenu date;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel employeeInfoPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton helpToolButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
